### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by rezacsedu** [smart-on-fhir/sample-patients-stu3#5]
Hi there,

Thanks for uploading the script and the dataset. Could you please tell me some potential use cases where this data can be used?

**Comment by gotdan** [comment]
The data is intended for testing SMART on FHIR applications (https://dev.smarthealthit.org). It's a combination of de-identified patient data and synthetic (fake) patient data so there are no restrictions on its use.

**Comment by rezacsedu** [comment]
@gotdan, thanks for these pointers.

**Comment by rezacsedu** [comment]
@gotdan could you please let me know how the data files in the data directory generated/collected/curated? Is there any Python script for that? Actually, I need to have 3 sets of data having the similar structure but slightly different values.
