### ISSUE TITLE
How were the data files in the data directory generated? 

### ISSUE THREAD

**Issue by rezacsedu** [smart-on-fhir/sample-patients-stu3#6]
Hi there,

How were the data files in the data directory generated? Is there any Python script for that? 
Also, there are some missing values. Why so?

**Comment by gotdan** [comment]
They're based on a set of de-identified data from a healthcare organization.  You may be interested in Mitre's open source Synthea tool (https://synthetichealth.github.io/synthea/), which is designed to generate realistic synthetic (fake) data.
